### ISSUE TITLE
Go言語を学びたい

### ISSUE THREAD

**Issue by teppei1959** [dangobro/Saturday-Night-Favorites#15]
# イベント名
Go言語勉強会

# 内容
Go言語を使い、SNSログインの仕組みを理解する

# 背景
SNSを利用するアプリケーションが多く、連携する際によく使われる言語だから

# 対象
誰でも

# 関連リンク

**Comment by telumo** [comment]
Go言語やりますか！

**Comment by teppei1959** [comment]
先生、教えてください！！

2020年5月9日(土) 9:43 telumo <notifications@github.com>:

**Comment by telumo** [comment]
[GoCute](http://cuto.unirita.co.jp/gostudy/)の第1章「Go言語の基本」までやりました。


一旦クローズします
